sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "8"

branches:
  only:
    - master

before_install:
  - cd my-owl-app

before_script:
  - npm install -g @angular/cli

script:
  - ng test
  - ng build --prod --aot
