import { Player } from '../models/player.model';
import { Role } from '../enums/role.enum';
import { TEAMS } from './teams.mock';

// TO-DO: Complete List
// tslint:disable:max-line-length
export const PLAYERS: Player[] = [
  { alias: 'Ado', firstName: 'Gihyeon', lastName: 'Chon', homeTown: 'Chungju, KR', team: TEAMS.SHANGHAI_DRAGONS, role: Role.OFFENCE },
  { alias: 'Agilities', firstName: 'Brady', lastName: 'Girardi', homeTown: 'Blairmore, CA', team: TEAMS.LOS_ANGELES_VALIANT, role: Role.OFFENCE },
  { alias: 'AimGod', firstName: 'Min-Seok', lastName: 'Kwon', homeTown: 'Busan, KR', team: TEAMS.BOSTON_UPRISING, role: Role.SUPPORT },
  { alias: 'aKm', firstName: 'Dylan', lastName: 'Bignet', homeTown: 'Angoulême, FR', team: TEAMS.DALLAS_FUEL, role: Role.OFFENCE },
  { alias: 'Altering', firstName: 'Min-Seok', lastName: 'Kwon', homeTown: 'Busan, KR', team: TEAMS.SHANGHAI_DRAGONS, role: Role.SUPPORT },
  { alias: 'Anamo', firstName: 'Tae-Sung', lastName: 'Jung', homeTown: 'Pohang, KR', team: TEAMS.NEW_YORK_EXCELSIOR, role: Role.SUPPORT },
  { alias: 'Architect', firstName: 'Minho', lastName: 'Park', homeTown: 'Seoul, KR', team: TEAMS.SAN_FRANCISCO_SHOCK, role: Role.OFFENCE },
  { alias: 'Arhan', firstName: 'WonHyeop', lastName: 'Jung', homeTown: 'KR', team: TEAMS.HOUSTON_OUTLAWS, role: Role.FLEX },
  { alias: 'Ark', firstName: 'Yeon-Jun', lastName: 'Hong', homeTown: 'Seoul, KR', team: TEAMS.NEW_YORK_EXCELSIOR, role: Role.SUPPORT },
  { alias: 'Asher', firstName: 'Jun-Sung', lastName: 'Choi', homeTown: 'Ulsan, KR', team: TEAMS.LOS_ANGELES_GLADIATORS, role: Role.OFFENCE },
  { alias: 'Avast', firstName: 'Connor', lastName: 'Prince', homeTown: 'Colleyville, TX, US', team: TEAMS.BOSTON_UPRISING, role: Role.SUPPORT },
  { alias: 'aWesomeGuy', firstName: 'Sung-Hoon', lastName: 'Kim', homeTown: 'Incheon, KR', team: TEAMS.FLORIDA_MAYHEM, role: Role.TANK },
  { alias: 'BABYBAY', firstName: 'Andrej', lastName: 'Francisty', homeTown: 'Chicago, IL, US', team: TEAMS.SAN_FRANCISCO_SHOCK, role: Role.OFFENCE },
  { alias: 'Bani', firstName: 'Christopher', lastName: 'Benell', homeTown: 'Ottawa, CA', team: TEAMS.HOUSTON_OUTLAWS, role: Role.SUPPORT },
  { alias: 'Bdosin', firstName: 'Seung-Tae', lastName: 'Choi', homeTown: 'Suwon, KR', team: TEAMS.LONDON_SPITFIRE, role: Role.SUPPORT },
  { alias: 'BigGoose', firstName: 'Benjamin Ville Aapeli', lastName: 'Isohanni', homeTown: 'Kokkola, FI', team: TEAMS.LOS_ANGELES_GLADIATORS, role: Role.SUPPORT },
  { alias: 'birdring', firstName: 'Ji-Hyeok', lastName: 'Kim', homeTown: 'Seoul, KR', team: TEAMS.LONDON_SPITFIRE, role: Role.OFFENCE },
  { alias: 'Bischu', firstName: 'Aaron', lastName: 'Kim', homeTown: 'Seoul, KR', team: TEAMS.LOS_ANGELES_GLADIATORS, role: Role.FLEX },
  { alias: 'Boink', firstName: 'Daniel', lastName: 'Pence', homeTown: 'Gurnee, IL, US', team: TEAMS.HOUSTON_OUTLAWS, role: Role.SUPPORT },
  { alias: 'Boombox', firstName: 'Isaac', lastName: 'Charles', homeTown: 'Boston, GB', team: TEAMS.PHILADELPHIA_FUSION, role: Role.SUPPORT },
  { alias: 'Bunny', firstName: 'Jun-Hyeok', lastName: 'Chae', homeTown: 'Suwon, KR', team: TEAMS.LOS_ANGELES_VALIANT, role: Role.OFFENCE },
  { alias: 'Carpe', firstName: 'Jae-Hyeok', lastName: 'Lee', homeTown: 'Daejeon, KR', team: TEAMS.PHILADELPHIA_FUSION, role: Role.OFFENCE },
  { alias: 'Chipshajen', firstName: 'Sebastian', lastName: 'Widlund', homeTown: 'Götene, SE', team: TEAMS.DALLAS_FUEL, role: Role.SUPPORT },
  { alias: 'Clockwork', firstName: 'Matthew', lastName: 'Dias', homeTown: 'Red Bank, NJ, US', team: TEAMS.HOUSTON_OUTLAWS, role: Role.OFFENCE },
  { alias: 'Closer', firstName: 'Won-Sik', lastName: 'Jung', homeTown: 'Seoul, KR', team: TEAMS.LONDON_SPITFIRE, role: Role.SUPPORT },

  { alias: 'cocco', firstName: 'Christian', lastName: 'Jonsson', homeTown: 'Härnösand, SE', team: TEAMS.DALLAS_FUEL, role: Role.TANK },
  { alias: 'Coolmatt', firstName: 'Matt', lastName: 'Iorio', homeTown: 'Laporte, IN, US', team: TEAMS.HOUSTON_OUTLAWS, role: Role.TANK },
  { alias: 'Custa', firstName: 'Scott', lastName: 'Kennedy', homeTown: 'Adelaide, AU', team: TEAMS.HOUSTON_OUTLAWS, role: Role.OFFENCE },
  { alias: 'CWoosH', firstName: 'Johan', lastName: 'Klingestedt', homeTown: 'Fagersta, SE', team: TEAMS.FLORIDA_MAYHEM, role: Role.FLEX },
  { alias: 'Daemin', firstName: 'Daemin', lastName: 'Kim', homeTown: 'KR', team: TEAMS.SHANGHAI_DRAGONS, role: Role.OFFENCE },
  { alias: 'Danteh', firstName: 'Dante', lastName: 'Cruz', homeTown: 'Chicago, IL, US', team: TEAMS.HOUSTON_OUTLAWS, role: Role.OFFENCE },
  { alias: 'DayFly', firstName: 'Jeong-Hwan', lastName: 'Park', homeTown: 'Mungyeong, KR', team: TEAMS.PHILADELPHIA_FUSION, role: Role.SUPPORT },
  { alias: 'dhaK', firstName: 'Daniel', lastName: 'Martinez Paz', homeTown: 'Gijón, ES', team: TEAMS.SAN_FRANCISCO_SHOCK, role: Role.SUPPORT },
  { alias: 'Diya', firstName: 'Weida', lastName: 'Lu', homeTown: 'Liaoning, CN', team: TEAMS.SHANGHAI_DRAGONS, role: Role.OFFENCE },
  { alias: 'EFFECT', firstName: 'Hyeon', lastName: 'Hwang', homeTown: 'Busan, KR', team: TEAMS.DALLAS_FUEL, role: Role.OFFENCE },
  { alias: 'Eqo', firstName: 'Josue', lastName: 'Corona', homeTown: 'Netenya, IL', team: TEAMS.PHILADELPHIA_FUSION, role: Role.OFFENCE },
  { alias: 'Fate', firstName: 'Pan-Seung', lastName: 'Koo', homeTown: 'Seoul, KR', team: TEAMS.LOS_ANGELES_VALIANT, role: Role.TANK },
  { alias: 'FCTFCTN', firstName: 'Russell', lastName: 'Campbell', homeTown: 'Midland, MI, US', team: TEAMS.HOUSTON_OUTLAWS, role: Role.TANK },
  { alias: 'Fearless', firstName: 'Eui-Seok', lastName: 'Lee', homeTown: 'Seoul, KR', team: TEAMS.SHANGHAI_DRAGONS, role: Role.TANK },
  { alias: 'Finnsi', firstName: 'Finnbjorn', lastName: 'Jonasson', homeTown: 'Reykjavík, IS', team: TEAMS.LOS_ANGELES_VALIANT, role: Role.FLEX },
  { alias: 'Fissure', firstName: 'Chan-Hyung', lastName: 'Baek', homeTown: 'Hwaseong, KR', team: TEAMS.LOS_ANGELES_GLADIATORS, role: Role.TANK },
  { alias: 'Fiveking', firstName: 'Zhaoyu', lastName: 'Chen', homeTown: 'Hunan, CN', team: TEAMS.SHANGHAI_DRAGONS, role: Role.SUPPORT },
  { alias: 'FLETA', firstName: 'Byung-Sun', lastName: 'Kim', homeTown: 'Namyangju, KR', team: TEAMS.SEOUL_DYNASTY, role: Role.OFFENCE },
  { alias: 'fragi', firstName: 'Joona', lastName: 'Laine', homeTown: 'Turku, FI', team: TEAMS.PHILADELPHIA_FUSION, role: Role.TANK },
  { alias: 'Freefeel', firstName: 'Peixuan', lastName: 'Xu', homeTown: 'Henan, CN', team: TEAMS.SHANGHAI_DRAGONS, role: Role.SUPPORT },
  { alias: 'Fury', firstName: 'Jun-Ho', lastName: 'Kim', homeTown: 'Seoul, KR', team: TEAMS.LONDON_SPITFIRE, role: Role.FLEX },
  { alias: 'Gambler', firstName: 'Jin-Woo', lastName: 'Heo', homeTown: 'Seoul, KR', team: TEAMS.SEOUL_DYNASTY, role: Role.SUPPORT },
  { alias: 'Gamsu', firstName: 'YoungJin', lastName: 'Noh', homeTown: 'Gyeongju, KR', team: TEAMS.BOSTON_UPRISING, role: Role.TANK },
  { alias: 'Geguri', firstName: 'Seyeon', lastName: 'Kim', homeTown: 'Daejeon, KR', team: TEAMS.SHANGHAI_DRAGONS, role: Role.TANK },
  { alias: 'Gesture', firstName: 'Jae-Hui', lastName: 'Hong', homeTown: 'Gunsan, KR', team: TEAMS.LONDON_SPITFIRE, role: Role.TANK }

  ];
